<?php
// Mendefinisikan variabel dengan angka 7
$angka = 7;

echo "Aku adalah angka " . $angka . ".<br>";

// Mengurangi angka 2
$kurang = $angka - 2;
echo "Jika aku di kurang 2, jumlahku sekarang " . $kurang . ".<br>";

// Mengalikan angka dengan 6
$kali = $angka * 6;
echo "Jika aku di kali 6, jumlahku sekarang " . $kali . ".<br>";

// Menambahkan angka dengan 5
$tambah = $angka + 5;
echo "Jika aku di tambah 5, jumlahku sekarang " . $tambah . ".<br>";
?>
